sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qq123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx07b343dae56f9659
    secret: 983694cf25f06ed73d53084139d534ce

file:
  upload-path: ${user.dir}/sky-server/images/

requestHeader: http://localhost:8080/images/

